  ####################################################################################################
  # Install prometheus+debian11
  ####################################################################################################

- name: "Play prometheus"
  hosts: servers
  vars:
    serviceName: "prometheus"
    userId: "prometheus"
    groupId: "prometheus"
    exec_command: "/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/data/prometheus --storage.tsdb.retention=2d"
    version: "2.40.1"
  become: true
  tasks:
    
    - name: Creating prometheus user group
      group:
        name: "{{groupId}}"
        state: present

    - name: Creating prometheus user
      user:
        name: "{{userId}}"
        group: "{{groupId}}"
        system: yes
        shell: "/sbin/nologin"
        comment: "{{userId}} nologin User"
        createhome: "no"
        state: present

    - name: Install prometheus
      unarchive:
        src: "https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes

    - name: Copy prometheus file to bin
      copy:
        src: "/tmp/prometheus-{{ version }}.linux-amd64/prometheus"
        dest: "/usr/local/bin/prometheus"
        owner: "{{userId}}"
        group: "{{groupId}}"
        remote_src: yes
        mode: 0755

    - name: Delete prometheus tmp folder
      file:
        path: '/tmp/prometheus-{{ version }}.linux-amd64'
        state: absent

    - name: —Åreate directory /etc/prometheus
      file:
        path=/etc/prometheus
        state=directory

    - name: config file
      template:
        src: file/prometheus.conf.j2
        dest: /etc/prometheus/prometheus.yml

    - name: Copy systemd init file
      template:
        src: file/init.service.j2
        dest: /etc/systemd/system/prometheus.service

    - name: chmod 777 /etc/prometheus
      file:
        path: "/etc/prometheus"
        owner: "{{userId}}"
        group: "{{groupId}}"
        mode: 0777

    - name: chmod 777 /usr/local/bin/prometheus
      file:
        path: "/usr/local/bin/prometheus"
        owner: "{{userId}}"
        group: "{{groupId}}"
        mode: 0777

    - name: chmod 777 /data/prometheus
      file:
        path: "/data/prometheus"
        owner: "{{userId}}"
        group: "{{groupId}}"
        mode: 0777

    - name: Start prometheus service
      service:
        name: prometheus
        state: started
        enabled: yes