  ####################################################################################################
  # Install zabbix 6.0-4+debian11
  ####################################################################################################
# https://github.com/alexnet123/9-2-Zabbix
- name: "Play zabbix"
  hosts: servers
  vars:
    bd_pass: dsfsdfd
  become: true
  tasks:
    - name: "Update repositories cache"
      shell: apt update && sudo apt -y full-upgrade

    - name: Install a .deb package from the internet
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-4%2Bdebian11_all.deb
    
    - name: "Install and configure the necessary dependencies"
      apt:
        pkg:
          - postgresql
          - zabbix-server-pgsql 
          - zabbix-frontend-php 
          - php7.4-pgsql 
          - zabbix-apache-conf 
          - zabbix-sql-scripts
          #- git
        state: latest
        update_cache: true

    # add bd zabbix
    - postgresql_db:
      name: zabbix

    # add user zabbix
    - name: Connect to acme database, create django user, and grant access to database and products table
      postgresql_user:
        db: zabbix
        name: zabbix
        password: {{ bd_pass }}
        priv: "CONNECT/products:ALL"
  
    # - name: "Change GitLab configurations"
    # - lineinfile:
    #     dest: /etc/gitlab/gitlab.rb
    #     regexp: '^external_url'
    #     line: "external_url 'http://{{ ansible_host }}'"

  
    - debug:
        msg:
        - "Gitlab URL http://{{ ansible_host }}"
        - "ssh {={ user }=}@{{ ansible_host }}" 

