    ####################################################################################################
    # Install nginx
    ####################################################################################################

- name: "Play2"
  hosts: servers
  become: true
  tasks:   
      
    - name: "Install - nginx"
      apt:
        name: nginx
        state: latest
  
    # - name: "Start service - nginx"
    #   service:
    #     name: nginx
    #     state: restarted

    - name: "Enabled - nginx"
      service:
        name: nginx
        enabled: yes

    ####################################################################################################
    # Local check URL - 200
    ####################################################################################################

    - name: "Local Check URL 200"
      uri: url=http://{{ ansible_host }}/ status_code=200
      delegate_to: localhost
      register: url_check
    
    - debug:
        msg:
        - "{{ url_check }}" 
        - "{{ url_check.status }}"
   ####################################################################################################

   
   ####################################################################################################
