---
- hosts: all
  become: yes

  vars:
    db_user: zabbix
    db_password: zabbix
    db_name: zabbix

  pre_tasks:
    - name: "Install packages"
      apt:
        pkg:
          - postgresql
          - python3-psycopg2
          - acl
        state: latest
        update_cache: true

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted

  tasks:
    - name: "Find out if PostgreSQL is initialized"
      stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: "Create app database"
      postgresql_db:
        state: present
        name: "{{ db_name }}"
      become: yes
      become_user: postgres

    - name: "Create db {{ db_name }}"
      postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become: yes
      become_user: postgres

    - name: "Grant db {{ db_user }} access to app db"
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: no
        privs: all
      become: yes
      become_user: postgres