  ####################################################################################################
  # Install zabbix 6.0-4+debian11
  ####################################################################################################
# https://github.com/alexnet123/9-2-Zabbix
- name: "Play zabbix"
  hosts: servers
  vars:
    db_user: zabbix
    db_password: zabbix
    db_name: zabbix

  become: true
  tasks:
    - name: "Update repositories cache"
      shell: apt update && sudo apt -y full-upgrade

    - name: Install zabbix.deb package from the internet
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-4%2Bdebian11_all.deb
    
    - name: "Install and configure the necessary dependencies"
      apt:
        pkg:
          - zabbix-server-pgsql 
          - zabbix-frontend-php 
          - php7.4-pgsql 
          - zabbix-apache-conf 
          - zabbix-sql-scripts
          - acl
          - unzip
          - tar
          - gzip
        state: latest
        update_cache: true

    - name: enable apache2
      service: 
        name: apache2 
        enabled: yes

    - name: enable zabbix
      service: 
        name: zabbix-server
        enabled: yes

    - name: Add postgresql user zabbix
      become: true
      become_user: postgres
      shell: su - postgres -c 'psql --command "CREATE USER {{ db_user }} WITH PASSWORD '\'{{ db_password }}\'';"'

    - name: Add postgresql db zabbix
      become: true
      become_user: postgres
      shell: su - postgres -c 'psql --command "CREATE DATABASE {{ db_name }} OWNER {{ db_user }};"'

    - name: Extract /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz ==> /usr/share/zabbix-sql-scripts/postgresql/server.sql
      shell: gunzip -c /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz > /usr/share/zabbix-sql-scripts/postgresql/server.sql


    - name: Add some dummy data to our database
      become: true
      become_user: postgres
      shell: psql {{ db_name }} < /usr/share/zabbix-sql-scripts/postgresql/server.sql
      

    #- name: "Change zabbix configurations"
    - lineinfile:
        dest: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBPassword='
        line: "DBPassword={{ db_password }}"

    - debug:
        msg:
        - "zabbix URL http://{{ ansible_host }}/zabbix"
        - "ssh {={ user }=}@{{ ansible_host }}"
        - "db_user: {{ db_user }}"
        - "db_password: {{ db_password }}"
        - "db_name: {{ db_name }}"

    - name: Reboot the machine
      shell: "sleep 5 && reboot"

  handlers:
    - name: restart zabbix
      service: name=zabbix state=restarted        

    - name: restart zabbix
      service: name=apache2 state=restarted



