    ####################################################################################################
    # Install gitlab
    ####################################################################################################
# https://computingforgeeks.com/install-and-configure-gitlab-ce-on-debian/
# - name: "Play gitlab Debian on x86_64 "
#   hosts: all
#   tasks:
  - name: "Update repositories cache"
    shell: apt update && sudo apt -y full-upgrade
  
  - name: "Install and configure the necessary dependencies"
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg 
        - lsb-release
        - perl
        - tzdata
        #- git
      state: latest
      update_cache: true

  - name: "Add the GitLab package repository and install the package - 1"
    shell: "curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash"

  - name: "Add the GitLab package repository and install the package - 2"
    shell: "apt install gitlab-ce"



  # - name: "Test key"
  #   shell: cat /etc/gitlab/initial_root_password  
  #   register: key_file
  # - debug:
  #     msg: "{{ key_file.stdout }}"


