# - name: "Play Docker Debian,Ubuntu on x86_64 / amd64, armhf, arm64, and Raspbian"
#   hosts: all
#   tasks:
  - name: "Install required system packages Docker"
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg 
        - lsb-release
      state: latest
      update_cache: true

  - name: Add signing key Docker - 1
    shell: sudo mkdir -p /etc/apt/keyrings
    
  - name: Add signing key Docker - 2
    shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

  - name: Add repository into sources list Docker
    shell: echo \ "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \ $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: Install Docker
    apt:
      name:
        - docker
        - docker.io
        - docker-compose
        - docker-registry
      state: latest
      update_cache: true 


